### ISSUE TITLE
codes for MCUnetV2

### ISSUE THREAD

**Issue by xiaxin1998** [mit-han-lab/tinyml#13]
Have you released codes of MCUnetV2?

**Comment by tonylins** [comment]
Hi, thanks for your interest! We have not released MCUNetV2-related code, but please let me know if you need help on any specific implementations.

**Comment by xiaxin1998** [comment]
Thanks for your reply. How you implement per-patch inference? I mean, how to implement per-patch CNN?

**Comment by tonylins** [comment]
In our paper, a CNN is split into two stages: the per-patch stage and the per-layer stage. For the per-patch stage, assume we use 2x2 patches, we first extract overlapping 2x2 patches from the input image, and run the per-patch stage on each patch respectively to get 4 output feature maps. The 4 feature maps are concatenated spatially and fed through the per-layer stage just like normal CNN inference.

**Comment by tonylins** [comment]
Close due to inactivity. Feel free to post issues under the new repo: https://github.com/mit-han-lab/mcunet.
