### ISSUE TITLE
Is the data in Figure 4 simulated or on board?

### ISSUE THREAD

**Issue by Menace-Dragon** [mit-han-lab/tinyml#20]
<img width="1106" alt="58274ef9bc20fb51b6e5bcb17834f17" src="https://user-images.githubusercontent.com/58941349/168782799-c4ce2354-2bac-4b2a-8001-78457770d933.png">

I found that MicroTVM seems to have no way to do autoTVM or auto scheduler for INT8 model against MCU.

![c2684b039ccf798b563f08056ea9f7a](https://user-images.githubusercontent.com/58941349/168783183-865e2a7c-fd02-4ad5-b941-7927ace97afa.jpg)

The figure shown above was the the answer from the TVM Community, which makes me confused.

**Comment by meenchen** [comment]
MicroTVM supports INT8 models on MCU. We follow this [tutorial](https://tvm.apache.org/2020/06/04/tinyml-how-tvm-is-taming-tiny) to measure the latency on the board.

**Comment by tonylins** [comment]
Close due to inactivity. Feel free to post issues under the new repo: https://github.com/mit-han-lab/mcunet.
