### ISSUE TITLE
Can I train my model with mcunet without using the horovod module

### ISSUE THREAD

**Issue by lufeiyang598** [mit-han-lab/tinyml#22]
As you can see, the horovod module cannot be installed on my computer. If I want to train a model without this module, what should I do?

**Comment by tonylins** [comment]
Hi, we are getting multiple feedback about the difficulty of installing `horovod`. We will soon update the repo to remove the `horovod` dependency. Please stay tuned!

**Comment by lufeiyang598** [comment]
Thanks for your response. I am looking forward to it.

**Comment by tonylins** [comment]
Hi, we have refactored the mcunet repo here: https://github.com/mit-han-lab/mcunet. Please take a look. Thanks!

**Comment by lufeiyang598** [comment]
Thanks for the update, your McUnet model performed well in tests, but I was wondering if I could use your code to train my own small McUnet model without using the Horovod module?




1572963206
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mit-han-lab/tinyml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 凌晨1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mit-han-lab/tinyml] Can I train my model with mcunet without using the horovod module (Issue #22)





 
Closed #22 as completed.

**Comment by lufeiyang598** [comment]
Thanks for the update, your McUnet model performed well in tests.
Now I have difficulties in training my own model. I want to train a miniature face recognition model similar to the vww model provided by you. Shoula I use generate_ Tflite module? I don't know how to use it yet.


---Original---
From: "Ji ***@***.***&gt;
Date: Fri, Jun 17, 2022 01:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/tinyml] Can I train my model with mcunet withoutusing the horovod module (Issue #22)




 
Hi, we have refactored the mcunet repo here: https://github.com/mit-han-lab/mcunet. Please take a look. Thanks!
