### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by jiaoyuming1** [mit-han-lab/tinyml#4]
Hello，I want to realization this project，but lack genNN.h and kernel_buffer.h and tinyengine_function.h 
How to get this files？

**Comment by tonylins** [comment]
Hi, we are still cleaning the TinyEngine part codebase. Stay tuned!

**Comment by maxiaotian520** [comment]
@tonylins Hello, this is an amazing project, very appreciate for the work you've done. I'm also trying to realize mcunet, but got failed. So could you provide a tutorial on it? thank you.

**Comment by tonylins** [comment]
Hi, we are currently cleaning the code for TinyEngine which will be released under the refactored repo: https://github.com/mit-han-lab/mcunet. Sorry for the waiting!
