### ISSUE TITLE
open source of  tiny engine

### ISSUE THREAD

**Issue by wangpengabc** [mit-han-lab/tinyml#6]
Hi, Will the tiny engine project be open-source?

**Comment by tonylins** [comment]
Sorry for the waiting! We are cleaning the code for TinyEngine which will be soon released under the refactored repo: https://github.com/mit-han-lab/mcunet. Please stay tuned! 

You can also sign up here to get notified: https://forms.gle/UW1uUmnfk1k6UJPPA
