### ISSUE TITLE
how long can we get tiny-engine code?

### ISSUE THREAD

**Issue by ydwang-good** [mit-han-lab/tinyml#7]
Hi, I would like to know approximately how long it will take to update the tiny-engine code  or rather the entire code？

**Comment by tonylins** [comment]
Sorry for the waiting! We are cleaning the code for TinyEngine which will be soon released under the refactored repo: https://github.com/mit-han-lab/mcunet. Please stay tuned!

You can also sign up here to get notified: https://forms.gle/UW1uUmnfk1k6UJPPA
