### ISSUE TITLE
How to measure the peak memory of ResNet50 in Table. 1 of MCUNet paper?

### ISSUE THREAD

**Issue by tanglang96** [mit-han-lab/tinyml#8]
Can you please tell me what tools are you using?

**Comment by tanglang96** [comment]
I tried to measure it by finding the maximum memory usage of all ops, and the memory usage of each op is calculated by adding the memory usage of all inputs and outputs of this op, I found that the peak memory of ResNet50 is reached at the second last convolution layer, which is ~9.6MB, is there a problem with my method?

**Comment by tanglang96** [comment]
The input image size is 1 x 3 x 224 x 224.

**Comment by tonylins** [comment]
Hi, I wrote a short script to measure the peak memory. What is the input and output activation shape of the second last layer according to your measurement? Thanks!

**Comment by tanglang96** [comment]
Thanks for your reply! The input and output size is 1 x 512 x 7 x 7 (total 196KB), but the weight size is 512 x 512 x 3 x 3 (9437KB, which is not counted according to your measurement), thus I got the peak memory ~9.6MB.

I've found your script and I guess that the 7.2MB peak memory of ResNet50 in your paper is reached by adding the final conv layer memory usage in a bottleneck block (input size 1 x 64 x 56 x 56 add output size 1 x 256 x 56 x 56, total 4014KB) and the residual size (1 x 256 x 56 x 56, 3211KB), thus has 7.2MB peak memory. But I'm still confusing in some aspects.

- Why not count the convolution weight when calculating the peak memory?
- From the op perspective, ```conv``` op has 4014KB memory usage (not count weight size, only inputs and outputs), ```add``` op has 6422KB memory usage (two inputs with size 1 x 256 x 56 x 56, inline implementation), thus the peak memory is 6422KB.

Thanks!

**Comment by tonylins** [comment]
Hi,

1. During the computation of convolution, the weights can be fetched from the Flash partially, so there is no need to store the entire weights in the memory. This is a common practice as done in https://arxiv.org/pdf/1906.05721.pdf

2. The residual connection in ResNets forms a two-branch structure. We need to keep the residual activation in the memory when computing the convolution. So the peak memory is the memory consumed by the convolution plus the residual activation size. You can also find the details in https://arxiv.org/pdf/1906.05721.pdf: "For each parallel branch in the
graph, for e.g. in MobileNet V2, we need to sum the activation storage of every pair of operations between the two
branches".

**Comment by tanglang96** [comment]
Thank you very much!

**Comment by tonylins** [comment]
I will close the issue for now. Feel free to reopen.
